fix: add base class to exception
pycyphal.application.file.RemoteFileError was introduced as common exception
base class/tag type to catch exceptions resulting from remote file operations
using the Cyphal remote file system interface.

In Python exceptions must inherit from BaseException, otherwise a TypeError
will occur:

TypeError: exceptions must derive from BaseException

RemoteFileError does not inherit from BaseException and can't thus be used in
except clauses.

This fix lets RemoteFileError inherit from RuntimeError, so that
RemoteFileError can be used as intended.

this fixes commit 40e14821285f48ad997cb3f7a8457d79a88db082

Signed-off-by: Hannes Weisbach <weisbach@neosat.de>